version: "3"
services:
  db:
    image: "postgres"
    container_name: "Local-Postgres"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test9988
      - POSTGRES_DB=pocdb
    ports:
      - "5432:5432"
    volumes:
      - /docker-tmp/postgres/data:/var/lib/postgresql/data
