version: '3'
services:
  scope:
    image: weaveworks/scope:1.13.1
    container_name: "Local-WeaveWorks"
    network_mode: "host"
    pid: "host"
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true"
