version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: "Local-Premetheus"
    volumes:
      - /docker-tmp/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
     - 9090:9090
