# Simple example of how to specify configuration files.

# Use the main Prometheus image.
FROM prom/prometheus

MAINTAINER ravi.nancherla@uhg.com


# Add in the configuration file from the local directory.
ADD prometheus.yml /Users/rredd16/Tools/Docker-Images/prometheus/prometheus-ihr-api.yml
