project:
  artifactId: spring-kakfa-poc
  name: spring-kakfa-poc
  version: 1.0.0
  description: Proving the theory about how kafka partitions and offsets works.


# Exposing all the actuator end points (Spring 2.0) #
management:
  endpoints:
    web:
      exposure:
        include:
          '*'

  # Exposing the restart & shutdown endpoint
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true

# For Spring Actuator /info endpoint
info:
  artifact: ${project.artifactId}
  name: ${project.name}
  description: ${project.description}
  version: ${project.version}

# Spring
spring:
  application:
    name: spring-kakfa-poc

  #Postgres dB configuration.
  datasource:
    platform: postgres
    url: "jdbc:postgresql://localhost:5432/pocdb"
    username: test
    password: test9988
    driver-class-name: org.postgresql.Driver

  #JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: poc_data
      auto-offset-reset: earliest

# Kafka topic configuration where listening from topic
topics:
  multipp: multi-partition-poc
  datasummary: billing-data-summary

# Scheduler expression configuration
scheduler:
  datasummarycron: 0 */2 * ? * *

# use a HTTP port 8080
server:
  port: 8085


---
spring:
  profiles: stage

server:
  port: 8080


---
spring:
  profiles: prod

server:
  port: 8080



