version: '3'
services:
  cassandra:
      image: cassandra:latest
      container_name: Local-Cassandra
      ports:
        - "9042:9042"
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
      restart: always
      volumes:
        - /docker-tmp/casandra/data:/var/lib/cassandra
