FROM openjdk:8
ADD build/libs/reporting-data-enrichment-service.jar reporting-data-enrichment-service.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "reporting-data-enrichment-service.jar"]docker build -t