project:
  artifactId: sb-kakfa-poc
  name: sb-kakfa-poc
  version: 1.0.0
  description: Proving the theory about how kafka partitions and offsets works in spring boot (micro service).


# Exposing all the actuator end points (Spring 2.0) #
management:
  endpoints:
    web:
      exposure:
        include:
          '*'

  # Exposing the restart & shutdown endpoint
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true

# For Spring Actuator /info endpoint
info:
  artifact: ${project.artifactId}
  name: ${project.name}
  description: ${project.description}
  version: ${project.version}

# Spring
spring:
  application:
    name: sb-kakfa-poc

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: poc_data
      auto-offset-reset: earliest

# Kafka topic configuration where listening from topic
topics:
  test: test

# use a HTTP port 8080
server:
  port: 8085


---
spring:
  profiles: stage

server:
  port: 8080


---
spring:
  profiles: prod

server:
  port: 8080



