version: '3'
services:
    mongodb:
      image: mongo:latest
      container_name: "Local-MongoDB"
      ports:
        - "27017:27017"
      volumes:
        - /Ravi-Projects/Docker-Images/mongoDB-Docker/data/db:/data/db
